stateMachine:
  name: omni-dw-salesForce-apis-process-records-STM
  definition:
    Comment: "State machine for process dynamo DB records"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: 
          Fn::GetAtt: ["ProcessFailedRecords","Arn"]
        Next: EndChoice
      EndChoice:
        Type: Choice
        Choices:
          - Variable: $.hasMoreData
            StringEquals: "false"
            Next: SuccessState
          - Variable: $.hasMoreData
            StringEquals: "true"
            Next: PublishEvents
      SuccessState:
        Type: Succeed